version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8837:80"
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/